extensions: non-zero exit code handling

diff --git a/prezto-modules/my-functions/functions/extensions b/prezto-modules/my-functions/functions/extensions
--- a/prezto-modules/my-functions/functions/extensions
+++ b/prezto-modules/my-functions/functions/extensions
@@ -14,6 +14,8 @@
 
 ###############################################################################
 ###############################################################################
+###############################################################################
+###############################################################################
 
 
 # Assign Python script to '$SCRIPT'
@@ -107,5 +109,27 @@ for k, v in reversed(counter_total.most_common()):
 EOF
 
 
-# Execute
+if [ $(command -v python3) != "" ]; then
+    PYTHON="python3"
+elif [ $(command -v python) != "" ]; then
+    PYTHON="python"
+else
+    echo "ERROR: Could not find a Python interpreter"
+    return 1
+fi
+
+
+###############################################################################
+###############################################################################
+###############################################################################
+###############################################################################
+
+# Execute script
 python3 -c "$SCRIPT" $@
+
+# Deal with non-zero exit code
+EXITCODE=$?
+if [ "$EXITCODE" -ne 0 ]; then
+    # This is a function, so 'return' not 'exit'.
+    return $EXITCODE
+fi
